OLD_FORMULATION = 0;
NEW_FORMULATION = 1;
SPECTRAL_EMBEDDING = 2;
KCCA_EMBEDDING = 3;
GUESS = 4;

METHOD_NAMES = {'Ours','Spectral Embedding','KCCA','Guess'};

MEAN_PRECISION = 1;
MEAN_RECALL = 2;
OVERALL_PRECISION = 3;
OVERALL_RECALL = 4;
DYNAMIC_PRECISION = 5;
MEAN_F1 = 6;
MEAN_MCC = 7;